package com.student.management.model;

import jakarta.persistence.*;
import jakarta.validation.constraints.Email;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;

/**
 * MODEL LAYER
 * ============
 * Student entity mapped to the 'students' table in the database.
 * Uses JPA/Hibernate annotations for ORM mapping.
 */
@Entity
@Table(name = "students")
public class Student {

    /**
     * Primary key — auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /**
     * Student's full name. Cannot be blank.
     */
    @NotBlank(message = "Name is required")
    @Size(min = 2, max = 100, message = "Name must be between 2 and 100 characters")
    @Column(nullable = false, length = 100)
    private String name;

    /**
     * Student's email address. Must be unique and valid format.
     */
    @NotBlank(message = "Email is required")
    @Email(message = "Please provide a valid email address")
    @Column(nullable = false, unique = true, length = 150)
    private String email;

    /**
     * Course the student is enrolled in.
     */
    @NotBlank(message = "Course is required")
    @Column(nullable = false, length = 100)
    private String course;

    // ─── Constructors ───────────────────────────────────────────────────────────

    /** Default constructor required by JPA. */
    public Student() {}

    /** Full constructor for creating student objects programmatically. */
    public Student(String name, String email, String course) {
        this.name   = name;
        this.email  = email;
        this.course = course;
    }

    // ─── Getters & Setters ──────────────────────────────────────────────────────

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getCourse() {
        return course;
    }

    public void setCourse(String course) {
        this.course = course;
    }

    // ─── toString ───────────────────────────────────────────────────────────────

    @Override
    public String toString() {
        return "Student{" +
               "id=" + id +
               ", name='" + name + '\'' +
               ", email='" + email + '\'' +
               ", course='" + course + '\'' +
               '}';
    }
}
